# https://alacritty.org/config-alacritty.html

import = ["/home/tirzasrwn/.config/alacritty/catppuccin-macchiato.toml"]
live_config_reload = true

[cursor]
blink_interval = 750
blink_timeout = 0
thickness = 0.15
unfocused_hollow = true
vi_mode_style = "None"

[cursor.style]
blinking = "Always"
shape = "Block"

[font]
builtin_box_drawing = true
size = 9.0

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Bold Italic"

[font.italic]
family = "FiraCode Nerd Font"
style = "Italic"

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

[shell]
program = "/usr/bin/zsh"
